repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
        # Run the linter.
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
        # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi ]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: uv run ./run_linting.sh
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: uv run ./run_pytest.sh
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: pytype
        name: pytype
        entry: uv run ./run_pytype.sh
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: robot
        name: robot framework test
        entry: uv run ./run_robot.sh
        language: system
        types: [python]
        pass_filenames: false

-   repo: local
    hooks:
    -   id: mypy
        name: mypy type checking
        entry: uv run ./run_mypy.sh
        language: system
        types: [python]
        pass_filenames: false
